name: Glance
version: "0.4.1"
slug: glance_dashboard
description: "A self-hosted dashboard that puts all your feeds in one place"
url: "https://github.com/glanceapp/glance"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - config
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web Interface
startup: application
options:
  log_level: info
schema:
  log_level: str
